INSERT INTO Reviews VALUES (1, 87, 99, 2, 'Loved it!');
INSERT INTO Reviews VALUES (2, 37, 57, 3, 'Excellent service!');
INSERT INTO Reviews VALUES (3, 43, 89, 4, 'Would definitely recommend.');
INSERT INTO Reviews VALUES (4, 70, 76, 2, 'Excellent service!');
INSERT INTO Reviews VALUES (5, 16, 20, 1, 'Amazing quality!');
INSERT INTO Reviews VALUES (6, 7, 52, 1, 'Could be better.');
INSERT INTO Reviews VALUES (7, 28, 97, 4, 'Excellent service!');
INSERT INTO Reviews VALUES (8, 76, 77, 2, 'Loved it!');
INSERT INTO Reviews VALUES (9, 28, 91, 1, 'Friendly staff and great service.');
INSERT INTO Reviews VALUES (10, 15, 50, 3, 'Will visit again.');
INSERT INTO Reviews VALUES (11, 24, 27, 2, 'Would definitely recommend.');
INSERT INTO Reviews VALUES (12, 32, 22, 2, 'Will visit again.');
INSERT INTO Reviews VALUES (13, 95, 23, 4, 'Excellent service!');
INSERT INTO Reviews VALUES (14, 80, 79, 2, 'Very satisfied with the experience.');
INSERT INTO Reviews VALUES (15, 14, 54, 2, 'Loved it!');
INSERT INTO Reviews VALUES (16, 33, 42, 3, 'Very satisfied with the experience.');
INSERT INTO Reviews VALUES (17, 29, 72, 2, 'Amazing quality!');
INSERT INTO Reviews VALUES (18, 72, 6, 4, 'Could be better.');
INSERT INTO Reviews VALUES (19, 42, 14, 4, 'Loved it!');
INSERT INTO Reviews VALUES (20, 28, 25, 5, 'Could be better.');
INSERT INTO Reviews VALUES (21, 29, 7, 5, 'Will visit again.');
INSERT INTO Reviews VALUES (22, 70, 47, 3, 'Not worth the money.');
INSERT INTO Reviews VALUES (23, 35, 95, 4, 'Will visit again.');
INSERT INTO Reviews VALUES (24, 12, 66, 1, 'Could be better.');
INSERT INTO Reviews VALUES (25, 72, 50, 1, 'Will visit again.');
INSERT INTO Reviews VALUES (26, 23, 61, 4, 'Very satisfied with the experience.');
INSERT INTO Reviews VALUES (27, 45, 48, 3, 'Will visit again.');
INSERT INTO Reviews VALUES (28, 85, 28, 4, 'Loved it!');
INSERT INTO Reviews VALUES (29, 90, 19, 5, 'Very satisfied with the experience.');
INSERT INTO Reviews VALUES (30, 46, 45, 5, 'Not worth the money.');
INSERT INTO Reviews VALUES (31, 48, 70, 1, 'Not what I expected.');
INSERT INTO Reviews VALUES (32, 81, 41, 2, 'Very satisfied with the experience.');
INSERT INTO Reviews VALUES (33, 18, 59, 2, 'Will visit again.');
INSERT INTO Reviews VALUES (34, 35, 13, 3, 'Very satisfied with the experience.');
INSERT INTO Reviews VALUES (35, 90, 72, 5, 'Could be better.');
INSERT INTO Reviews VALUES (36, 76, 56, 5, 'Friendly staff and great service.');
INSERT INTO Reviews VALUES (37, 15, 3, 3, 'Could be better.');
INSERT INTO Reviews VALUES (38, 58, 96, 5, 'Friendly staff and great service.');
INSERT INTO Reviews VALUES (39, 55, 30, 3, 'Not worth the money.');
INSERT INTO Reviews VALUES (40, 6, 93, 4, 'Could be better.');
INSERT INTO Reviews VALUES (41, 5, 58, 1, 'Will visit again.');
INSERT INTO Reviews VALUES (42, 13, 12, 3, 'Amazing quality!');
INSERT INTO Reviews VALUES (43, 74, 93, 1, 'Will visit again.');
INSERT INTO Reviews VALUES (44, 74, 36, 2, 'Friendly staff and great service.');
INSERT INTO Reviews VALUES (45, 5, 12, 3, 'Very satisfied with the experience.');
INSERT INTO Reviews VALUES (46, 9, 27, 4, 'Will visit again.');
INSERT INTO Reviews VALUES (47, 17, 24, 3, 'Very satisfied with the experience.');
INSERT INTO Reviews VALUES (48, 92, 54, 4, 'Would definitely recommend.');
INSERT INTO Reviews VALUES (49, 89, 88, 2, 'Not worth the money.');
INSERT INTO Reviews VALUES (50, 40, 15, 1, 'Loved it!');
INSERT INTO Reviews VALUES (51, 21, 66, 1, 'Loved it!');
INSERT INTO Reviews VALUES (52, 68, 15, 3, 'Would definitely recommend.');
INSERT INTO Reviews VALUES (53, 81, 34, 5, 'Not worth the money.');
INSERT INTO Reviews VALUES (54, 93, 76, 5, 'Very satisfied with the experience.');
INSERT INTO Reviews VALUES (55, 96, 52, 1, 'Amazing quality!');
INSERT INTO Reviews VALUES (56, 37, 80, 5, 'Not worth the money.');
INSERT INTO Reviews VALUES (57, 2, 87, 4, 'Excellent service!');
INSERT INTO Reviews VALUES (58, 99, 83, 4, 'Very satisfied with the experience.');
INSERT INTO Reviews VALUES (59, 1, 1, 2, 'Friendly staff and great service.');
INSERT INTO Reviews VALUES (60, 70, 60, 4, 'Could be better.');
INSERT INTO Reviews VALUES (61, 52, 77, 4, 'Could be better.');
INSERT INTO Reviews VALUES (62, 77, 43, 4, 'Very satisfied with the experience.');
INSERT INTO Reviews VALUES (63, 14, 71, 3, 'Not what I expected.');
INSERT INTO Reviews VALUES (64, 57, 89, 1, 'Amazing quality!');
INSERT INTO Reviews VALUES (65, 28, 83, 3, 'Friendly staff and great service.');
INSERT INTO Reviews VALUES (66, 61, 63, 5, 'Loved it!');
INSERT INTO Reviews VALUES (67, 68, 6, 5, 'Not what I expected.');
INSERT INTO Reviews VALUES (68, 73, 8, 2, 'Excellent service!');
INSERT INTO Reviews VALUES (69, 84, 34, 2, 'Amazing quality!');
INSERT INTO Reviews VALUES (70, 17, 24, 4, 'Very satisfied with the experience.');
INSERT INTO Reviews VALUES (71, 35, 88, 2, 'Not worth the money.');
INSERT INTO Reviews VALUES (72, 45, 53, 5, 'Not worth the money.');
INSERT INTO Reviews VALUES (73, 8, 41, 3, 'Not worth the money.');
INSERT INTO Reviews VALUES (74, 93, 27, 3, 'Amazing quality!');
INSERT INTO Reviews VALUES (75, 91, 17, 1, 'Amazing quality!');
INSERT INTO Reviews VALUES (76, 51, 57, 1, 'Will visit again.');
INSERT INTO Reviews VALUES (77, 55, 71, 5, 'Excellent service!');
INSERT INTO Reviews VALUES (78, 43, 47, 5, 'Could be better.');
INSERT INTO Reviews VALUES (79, 7, 69, 2, 'Very satisfied with the experience.');
INSERT INTO Reviews VALUES (80, 30, 6, 3, 'Friendly staff and great service.');
INSERT INTO Reviews VALUES (81, 48, 26, 2, 'Loved it!');
INSERT INTO Reviews VALUES (82, 6, 53, 5, 'Friendly staff and great service.');
INSERT INTO Reviews VALUES (83, 20, 59, 5, 'Loved it!');
INSERT INTO Reviews VALUES (84, 12, 17, 4, 'Could be better.');
INSERT INTO Reviews VALUES (85, 74, 74, 4, 'Could be better.');
INSERT INTO Reviews VALUES (86, 56, 26, 5, 'Excellent service!');
INSERT INTO Reviews VALUES (87, 2, 82, 1, 'Excellent service!');
INSERT INTO Reviews VALUES (88, 17, 32, 2, 'Excellent service!');
INSERT INTO Reviews VALUES (89, 93, 53, 3, 'Will visit again.');
INSERT INTO Reviews VALUES (90, 72, 1, 1, 'Not worth the money.');
INSERT INTO Reviews VALUES (91, 42, 33, 4, 'Excellent service!');
INSERT INTO Reviews VALUES (92, 60, 15, 4, 'Very satisfied with the experience.');
INSERT INTO Reviews VALUES (93, 7, 26, 1, 'Not worth the money.');
INSERT INTO Reviews VALUES (94, 3, 35, 3, 'Friendly staff and great service.');
INSERT INTO Reviews VALUES (95, 76, 45, 3, 'Loved it!');
INSERT INTO Reviews VALUES (96, 25, 46, 1, 'Very satisfied with the experience.');
INSERT INTO Reviews VALUES (97, 74, 30, 5, 'Loved it!');
INSERT INTO Reviews VALUES (98, 34, 13, 3, 'Friendly staff and great service.');
INSERT INTO Reviews VALUES (99, 94, 97, 1, 'Not worth the money.');
INSERT INTO Reviews VALUES (100, 20, 35, 1, 'Not what I expected.');
